name=SynthWave '84
group=futuristic
fx=glow
background=#262335
foreground=#ffffff
cursor=#03edf9
color0=#382c4d
color1=#fe4450
color2=#72f1b8
color3=#fede5d
color4=#34d3fb
color5=#f92aad
color6=#36f9f6
color7=#f2ebe0
color8=#7b6a98
color9=#ff7d86
color10=#c6ffe5
color11=#fff0b4
color12=#aaeeff
color13=#ffa8df
color14=#9efffd
color15=#f1f1f1
